config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #devise_for :users, skip: [:sessions]

  #as :user do
  #  get 'login', to: 'pages#login', as: :new_user_session
  #  get 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  #end

  root to: "pages#index" 

  resources :products
  resources :categories

  #resources :billings, only: [:index, :show, :destroy]
  #workspace
  
  #namespace :workspace do
  #  resources :boards
  #end
  
  #resources :workspace
  


  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end

  #draw :administration
  draw :api

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  
  def load_defaults
    if self.new_record?
      self.status = "active"
    end
  end

end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  ROLES = [
    "ADMIN",
    "USER"
  ]


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:login]


  attr_accessor :login

  validates :role, presence: true, inclusion: { in: ROLES}
  

  before_validation :load_defaults

  def load_defaults
    if self.new_record?
      if self.new_record?
        self.role == "USER" if self.role.nil?
      end

    end
  end

  def admin?
    role == "ADMIN"
  end



  def login=(login)
    @login  = login
  end

  def login
    @login || self.username || self.email
  end





  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { value: login.downcase }]).first 
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end


end

app/models/workgroup_file.rb
class WorkgroupFile < ApplicationRecord
  belongs_to :user
end

app/controllers/api/v1/product_searchs_controller.rb
module Api
  module V1 
    class ProductSearchsController < ApiController
      def search
         
        refference_number  = params[:prod_ref]
          
          result = ActiveRecord::Base.connection.execute(<<-EOS).to_a
                     select * from products where refference_number like '%prod01%'
                  
                   EOS

    
      
        
        if result.count > 0 
          render json: { result: result }
        else
        
          render json: { message: "error" }, status: 400
        end
      end
    end
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  protect_from_forgery with: :null_session
  
  def authenticate_app_request!
    if request.headers["X-KOINS-APP-AUTH-SECRET"].blank?
      render json: { message: "unauthenticated", full_messages: ["unauthenticated"] }, status: 400
    elsif request.headers["X-KOINS-APP-AUTH-SECRET"] != app_auth_secret
      render json: { message: "invalid auth token", full_messages: ["invalid auth token"] }, status: 400
    end
  end
  
  def authenticate_api_member!

    if access_token.blank?
      render json: { message: "unauthenticated" }, status: 400
    else
      @member = Member.where(access_token: access_token).first
    end
  end

  def authenticate_core_user!
    if params[:user_id].blank?
      render json: { message: "user_id required" }, status: 400
    else
      @core_user = User.find_by_id(params[:user_id])

      if @core_user.blank?
        render json: { message: "core user not found" }
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout :layout_by_resource
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  def layout_by_resource
    
        
    if devise_controller?
      "landing"
    else
      "application" 
    end
  end


  def authorize_admin!
    if !current_user.admin?
      flash[:error] = "Unauthorized"
      redirect_to root_path
    end
  end


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:login, :username, :email, :password, :first_name])
    devise_parameter_sanitizer.permit(:sign_in, keys:[:login, :username, :email, :password, :first_name])
    #devise_parameter_sanitizer.permit(:account_update, keys:[:username, :email, :password, :password_confirmation, :current_password])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
  def new
    @category = Category.new
  end
  def create
    @category= Category.new(category_params)

      if @category.save
        redirect_to categories_path
      else
        render "new"
        
      end
    
    
  end
  def show
  end
  def edit
    @category = Category.find(params[:id])
  end
  def update
    @category = Category.find(params[:id])
      
    if @category.update(category_params) 
      redirect_to categories_path
    else
        render "edit"
    end
  end

  def destroy
    @category = Category.find(params[:id])

    @category.destroy!
    redirect_to categories_path
  end

  private
  def category_params
    params.require(:category).permit!
    
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index
      
    #@products = Product.all
    if params[:new_search].present?
      config={
          refference_number: params[:new_search]
      }
      @data = ::Pages::GenerateRefference.new(config: config).execute!
      
      
    end

    

  end



end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
  def new
    @product = Product.new
  end
  def create
    @product = Product.new(product_params)

      if @product.save
        redirect_to products_path
      else
        render "new"
        
      end
    
    
  end
  def show
    @product = Product.find(params[:id])
  end
  def edit
    @product = Product.find(params[:id])
  end
  def update
    @product = Product.find(params[:id])
      
    if @product.update(product_params) 
      redirect_to products_path
    else
        render "edit"
    end
  end

  def destroy
    @product = Product.find(params[:id])

    @product.destroy!
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit!
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.haml
= simple_form_for category do |f|
  = f.input :name, input_html: { class: "form-control"  }
  = f.input :code, input_html: { class: "form-control"  }
  %hr
  = button_tag type: :submit, class: "btn btn-primary" do
    Save
  = link_to products_path, class: "btn btn-default" do
    Cancel

app/views/categories/_index_list.html.haml
%table#data-table.display.table.table-bordered.table-hover.table-sm
  %thead
    %tr
      %th Name
      %th Code
      %th Action
  %tbody 
    - @categories.each do |category|
      %tr
        %td
          #{category.name.upcase}
        %td
          #{category.code.upcase}
        %td
          .btn-group
            = link_to edit_category_path(category), class: 'btn btn-sm btn-info' do
              .fa.fa-pencil-alt
              Edit
          .btn-group
            = link_to category_path(category), method: :delete  ,class: 'btn btn-sm btn-danger', data: { confirm: "Are you sure?" } do
              .fa.fa-pencil-alt
              Delete

app/views/categories/edit.html.haml
%section.content
.content-wrapper
  .content-header
    .container-fluid
      .row.mb-2
        .col-sm-6
          %h1.m-0.text-dark Products
        .col-sm-6
          %ol.breadcrumb.float-sm-right
            %li.breadcrumb-item
              %a{:href => "#"} Home
            %li.breadcrumb-item
              %a{:href => "#"} Products
            %li.breadcrumb-item.active Modified Product


  %section.content
    .container-fluid
      .card
        .card-body
          = render partial: "form", locals: { category: @category  }

app/views/categories/index.html.haml
%section.content
.content-wrapper
  .content-header
    .container-fluid
      .row.mb-2
        .col-sm-6
          %h1.m-0.text-dark Categories
        .col-sm-6
          %ol.breadcrumb.float-sm-right
            %li.breadcrumb-item
              %a{:href => "#"} Home
            %li.breadcrumb-item.active Categories

  %section.content
    .container-fluid
      .card
        .card-body
          = render partial: "index_list"
        
        .card-footer
          = link_to new_category_path, class: 'btn btn-danger' do
            .fa.fa-times
            New

app/views/categories/new.html.haml
%section.content
.content-wrapper
  .content-header
    .container-fluid
      .row.mb-2
        .col-sm-6
          %h1.m-0.text-dark Products
        .col-sm-6
          %ol.breadcrumb.float-sm-right
            %li.breadcrumb-item
              %a{:href => "#"} Home
            %li.breadcrumb-item
              %a{:href => "#"} Products
            %li.breadcrumb-item.active New Product


  %section.content
    .container-fluid
      .card
        .card-body
          = render partial: "form", locals: { category: @category  }


          

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Myapp
    = csrf_meta_tags
    = csp_meta_tag

    %meta{ name: "viewport", content: "width=device-width, initial-scale=1, shrink-to-fit=no" }
    %meta{ name: "parameters", content: "#{{ route: "#{params[:controller]}/#{params[:action]}", payload: (@payload || {}) }.to_json}" } 
    = stylesheet_link_tag 'application'
    = javascript_pack_tag 'application'
  
  %body.hold-transition.sidebar-mini.layout-fixed
  .wrapper
    = render partial: "shared/sidebar"
    = render partial: "shared/admin_nav"
    
    %section.content 
      = yield
      //= render partial: "shared/admin_footer"

app/views/layouts/landing.html.haml
!!!
%html
  %head
    %title Myapp
    = csrf_meta_tags
    = csp_meta_tag

    %meta{ name: "viewport", content: "width=device-width, initial-scale=1, shrink-to-fit=no" }
    %meta{ name: "parameters", content: "#{{ route: "#{params[:controller]}/#{params[:action]}", payload: (@payload || {}) }.to_json}" } 
    = stylesheet_link_tag 'application'
    = javascript_pack_tag 'application'
  
  %body.layout-fixed
    .wrapper
      .c-body
        %main.c-main
          .container-fluid
            = yield
      //= render partial: "shared/admin_footer"

app/views/pages/_index_list.html.haml
- if @data.present?
  %hr
    %table#data-table.display.table.table-bordered.table-hover.table-sm
      %thead
        %tr
          %th Refference Number
          %th Name
          %th Category
          %th Price
      
      %tbody 
        - @data.each do |d|

          - d[:list].each do |l|
            %tr
              %td
                #{l[:refference_number]}
              %td
                #{l[:name]}
              %td
                #{l[:category]}
              %td
                #{l[:destination]}

      

app/views/pages/index.html.haml
= form_tag "", method: 'GET' do
  .content-wrapper
    .content-header
      .container-fluid
        .row.mb-2
          .col-sm-6
            %h1.m-0.text-dark Dashboard
          .col-sm-6
            %ol.breadcrumb.float-sm-right
              %li.breadcrumb-item
                %a{:href => "#"} Home
              %li.breadcrumb-item.active Dashboard

    %section.content
      .container-fluid
        .row
          .col
            .card
              .card-body
                %center
                  %label
                    Refference Number
                    = text_field_tag :new_search, "", id: "input-search" , class: "form-control", placeholder: "Reference #"
                %center
                  .btn-group
                    = button_tag type: 'submit', class: 'btn btn-info btn-block' do
                      Search
      
                = render partial: "index_list"

app/views/pages/login.html.haml
.container
  .row
    .col
      #login-form
        .card
          .card-body
            %center
              Jef Drilon
            %hr
            .input-group
              .input-group-prepend
                .input-group-text
                  .fa.fa-user
              = text_field_tag :username, "", id: "input-username", class: "form-control", placeholder: "USERNAME"
            .input-group
              .input-group-prepend
                .input-group-text
                  .fa.fa-key
              = password_field_tag :password, "", id: "input-password", class: "form-control", placeholder: "PASSWORD"
            %hr
            .row
              .col
                .message
                %center
                  .btn-group
                    #btn-login.btn.btn-primary
                      .fa.fa-sign-in-alt
                      Login to System

app/views/products/_form.html.haml
= simple_form_for product do |f|
  = f.input :refference_number, input_html: { class: "form-control"  }
  = f.input :name, input_html: { class: "form-control"  }
  = f.association :category, input_html: { class: "form-control"  }
  = f.input :product_price, input_html: { class: "form-control"  }
  %hr
  = button_tag type: :submit, class: "btn btn-primary" do
    Save
  = link_to products_path, class: "btn btn-default" do
    Cancel

app/views/products/_index_list.html.haml
%table#data-table.display.table.table-bordered.table-hover.table-sm
  %thead
    %tr
      %th Refference Number
      %th Name
      %th Category
      %th Price
      %th Action
  %tbody 
    - @products.each do |product|
      %tr
        %td
          #{product.refference_number.upcase}
        %td
          #{product.name.upcase}
        %td
          #{product.category.name.upcase}
        %td
          #{product.product_price.upcase}
        %td
          
          .btn-group
            = link_to edit_product_path(product), class: 'btn btn-sm btn-info' do
              .fa.fa-pencil-alt
              Edit
          .btn-group
            = link_to product_path(product), method: :delete  ,class: 'btn btn-sm btn-danger', data: { confirm: "Are you sure?" } do
              .fa.fa-pencil-alt
              Delete

app/views/products/_show_details.html.haml
.table-responsive
  %table.table-bordered.table
    %thead
      %tr
        %th Name
        %th Code
    %tbody
      %tr
        %td #{@product.name }
      
        

app/views/products/edit.html.haml
%section.content
.content-wrapper
  .content-header
    .container-fluid
      .row.mb-2
        .col-sm-6
          %h1.m-0.text-dark Products
        .col-sm-6
          %ol.breadcrumb.float-sm-right
            %li.breadcrumb-item
              %a{:href => "#"} Home
            %li.breadcrumb-item
              %a{:href => "#"} Products
            %li.breadcrumb-item.active Modified Product


  %section.content
    .container-fluid
      .card
        .card-body
          = render partial: "form", locals: { product: @product  }

app/views/products/index.html.haml
%section.content
.content-wrapper
  .content-header
    .container-fluid
      .row.mb-2
        .col-sm-6
          %h1.m-0.text-dark Products
        .col-sm-6
          %ol.breadcrumb.float-sm-right
            %li.breadcrumb-item
              %a{:href => "#"} Home
            %li.breadcrumb-item.active Products

  %section.content
    .container-fluid
      .card
        .card-body
          = render partial: "index_list"
        
        .card-footer
          = link_to new_product_path, class: 'btn btn-danger' do
            .fa.fa-times
            New

app/views/products/new.html.haml
%section.content
.content-wrapper
  .content-header
    .container-fluid
      .row.mb-2
        .col-sm-6
          %h1.m-0.text-dark Products
        .col-sm-6
          %ol.breadcrumb.float-sm-right
            %li.breadcrumb-item
              %a{:href => "#"} Home
            %li.breadcrumb-item
              %a{:href => "#"} Products
            %li.breadcrumb-item.active New Product


  %section.content
    .container-fluid
      .card
        .card-body
          = render partial: "form", locals: { product: @product  }


          

app/views/products/show.html.haml
%section.content
.content-wrapper
  .content-header
    .container-fluid
      .row.mb-2
        .col-sm-6
          %h1.m-0.text-dark Areas
        .col-sm-6
          %ol.breadcrumb.float-sm-right
            %li.breadcrumb-item
              %a{:href => "#"} Home
            %li.breadcrumb-item
              %a{:href => "#"} Area
            %li.breadcrumb-item.active New Area
  %section.content
    .container-fluid
      .card
        .card-body
          = render partial: "show_details"

app/views/shared/_admin_footer.html.haml
%footer.main-footer
  %strong
    Copyright © 2021
    = succeed "." do
      %a{:href => "http://adminlte.io"} jefDrilon
  All rights reserved.
  .float-right.d-none.d-sm-inline-block
    %b Version
    0.0.1

app/views/shared/_admin_nav.html.haml
%aside.main-sidebar.sidebar-dark-primary.elevation-4
  %a.brand-link{:href => "index3.html"}
    
    %span.brand-text.font-weight-light myApp

  %nav.mt-2
    %ul.nav.nav-pills.nav-sidebar.flex-column{"data-accordion" => "false", "data-widget" => "treeview", :role => "menu"}
      %li.nav-item
        %a.nav-link{:href => root_path}
          %i.nav-icon.fas.fa-tachometer-alt
          %p My Dashboard
      %li.nav-item
        %a.nav-link{:href =>  products_path}
          %i.nav-icon.far.fas.fa-layer-group
          %p Products
      %li.nav-item
        %a.nav-link{:href =>  categories_path}
          %i.nav-icon.far.fas.fa-layer-group
          %p Categoy

        

app/views/shared/_sidebar.html.haml
%nav.main-header.navbar.navbar-expand.navbar-white.navbar-light
  %ul.navbar-nav
    %li.nav-item
      %a.nav-link{"data-widget" => "pushmenu", :href => "#", :role => "button"}
        %i.fas.fa-bars


  %ul.navbar-nav.ml-auto
    %li.nav-item.dropdown
      %a.nav-link{"data-toggle" => "dropdown", :href => "#"}
        Jef Drilon
      .dropdown-menu.dropdown-menu-lg.dropdown-menu-right
        %span.dropdown-item.dropdown-header My Account
        .dropdown-divider
        %a.dropdown-item{:href => "#"}
          %i.fas.fa-users
          Teams
        %a.dropdown-item{:href => "#"}
          %i.fas.fa-user-plus
          Invite Members
        %a.dropdown-item{:href => "#"}
          %i.fas.fa-key
          Log out
          

app/views/shared/_sidebar_draft.html.haml
%nav.main-header.navbar.navbar-expand.navbar-white.navbar-light
  %ul.navbar-nav
    %li.nav-item
      %a.nav-link{"data-widget" => "pushmenu", :href => "#", :role => "button"}
        %i.fas.fa-bars
    %li.nav-item.d-none.d-sm-inline-block
      %a.nav-link{:href => "index3.html"} Home
    %li.nav-item.d-none.d-sm-inline-block
      %a.nav-link{:href => "#"} Contact



%aside.main-sidebar.sidebar-dark-primary.elevation-4
  %nav.mt-2
    %ul.nav.nav-pills.nav-sidebar.flex-column{"data-accordion" => "false", "data-widget" => "treeview", :role => "menu"}
      %li.nav-item.menu-open
        %a.nav-link.active{:href => "#"}
          %i.nav-icon.fas.fa-tachometer-alt
          %p
            Dashboard
            %i.right.fas.fa-angle-left

        %ul.nav.nav-treeview
          %li.nav-item
            %a.nav-link.active{:href => administration_areas_path}
              %p 
                Areas
          %li.nav-item
            %a.nav-link.active{:href => "./index.html"}
              %i.far.fa-circle.nav-icon
                %p Dashboard v2

          %li.nav-item
            %a.nav-link.active{:href => "./index.html"}
              %i.far.fa-circle.nav-icon
                %p Dashboard v3